BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `lesson` (
	`_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`courseid`	INTEGER,
	`title`	TEXT,
	`section0`	TEXT,
	`section1`	TEXT,
	`section2`	TEXT,
	`section3`	TEXT,
	`section4`	TEXT,
	`section5`	TEXT,
	`section6`	TEXT,
	`section7`	TEXT,
	`section8`	TEXT,
	`section9`	REAL,
	`questions`	INTEGER,
	`result`	INTEGER DEFAULT 0,
	`nsections`	INTEGER DEFAULT 0
);
INSERT INTO `lesson` VALUES (1,1,'Passwords','Introduction<<-->>We continuously entrust more and more information to our social networks, considering them inviolable places thanks to the protection offered by passwords. However, they are only keywords and the bad guys, given enough time, could discover them and steal our data. Many still use as a password the name of their girlfriend or that of their pet and the most unwary use the timeless sequence "123456" (which is the password most used in recent years). Discovering such passwords is a breeze even for a novice hacker.
 The first step to protect your online privacy is therefore the creation of a secure password, a password that can not be discovered by a program or a person in a short space of time.','Guidelines<<-->>First, choose a fairly long password (composed of at least 15-20 characters) alternating letters, both uppercase and lowercase, numbers, punctuation marks and symbols (e.g. !,?,£,$,#,% etc.). In fact, by using a sequence of characters that does not make up a meaningful word or phrase, you will discourage attempts by attackers who make attacks based on dictionaries. Such attacks are based on searching for your password in very long common word lists, or a dictionary.
 Another very important precaution is to not use words as passwords that can somehow be guessed by other people. To go a little further, do not use the names of your family members, your date of birth or wedding anniversary or other data that is easily traceable to you.
 It is also a good idea to constantly update your passwords (possibly at least once every 2-3 months), since no password is 100% secure. Another aspect not to be overlooked is that of using different passwords for each account: if you do that, even if they should unfortunately intercept one of your access keys, the security of other accounts would not be compromised.','Creating a secure password<<-->>After having seen some general advice on how to choose a sufficiently secure password, the time has come to move from theory to practice. In fact, there are several useful tools to choose a secure password. These are basically automatic password generators that, complying with the guidelines of the previous chapter, create quite secure access keys.
 One of the most famous password generators is Password Chart. As the name of this service indicates, it allows the creation of access keys using transcoding technique. How does this work? In practice, the user types a sentence that allows you to generate the scheme that will be used to create the password, then types the word that will be used as a reference for creating the password and, at that point, the software will associate with each letter of the alphabet a specific combination of numbers, letters and symbols, thus creating a fairly secure password.','Password Manager<<-->>Passwords of this type, however, can be very difficult to remember and are likely to be forgotten after the first use. It is therefore necessary to rely on some tool to help our memory. By discarding the conventional post-it, which are easy to lose and can be found by bad guys, you can make good use of so-called password managers, or special programs that, like a sort of "virtual safe", store the passwords of their accounts. Using a password manager has a double benefit: first, the passwords are kept safe (and not a little!) And, other important aspect, we do not have the problem of remembering all the other passwords because you can open these "virtual safes", remembering only one main password.',NULL,NULL,NULL,NULL,NULL,NULL,'The most used password in recent years is:<->123456<->Abcdef<->Qwerty123<->password<<-->>Are there really safe passwords?<->No, any password can be found in a time long enough<->Yes, mine is<->No, because all the passwords have already been used<->Yes, but no one has ever found one<<-->>The dictionary attacks try to guess our password:<->lists of commonly used words<->Using dictionaries of various different languages<->Using words in alphabetical order, as in a dictionary<->With words generated at random by a computer<<-->>Password Chart allows us to:<->Generate really secure passwords<->Access our passwords without using any<->Attach the accounts of our email contacts<->Monitor the security of our password<<-->>Entrust passwords to a password manager is very convenient and fast, but not very secure<->F<<-->>Use UPPERCASE and lowercase characters in our password increases its resistance to attacks<->T<<-->>It is convenient to use the names of our family members in our passwords, because they are easy to remember and, after all, not easy to guess by foreign users<->F<<-->>Password Chart is a useless and discouraging system, because it generates incomprehensible passwords<->F<<-->>To access our password manager it is necessary to remember a single, long master key<->T<<-->>It is strongly recommended to change your password after a few months of use<->T',0,4);
INSERT INTO `lesson` VALUES (3,2,'Virus','Cosa sono e come si diffondono<<-->>Un virus informatico è simile ad un virus biologico: si tratta di un programma progettato e realizzato per causare danni all’interno del dispositivo infettato. I primi virus nascono insieme all’informatica moderna (1980) e nel corso dei decenni si sono evoluti per meglio adattarsi a un ambiente in continua trasformazione.  Da un punto di vista del loro ciclo di vita, dopo la fase "riproduttiva", i virus informatici iniziano a svolgere attività di varia natura: distruttive e/o di ostruzionismo. Come si diffondono? Tramite il trasferimento di file infetti da un computer ad un altro, e, cosa ancor più grave, possono attaccare computer collegati fra loro in rete.','Virus di prima generazione e virus recenti<<-->>Mentre i virus della prima generazione attaccavano soltanto i file eseguibili (che nel sistema operativo DOS sono riconoscibili in quanto hanno un estensione .COM o .EXE), i virus attuali sono in grado di inquinare molti altri tipi di file nonché di cambiare le istruzioni del BIOS caricate in RAM, di diffondersi attraverso gli stessi supporti fisici contenuti nel PC e di danneggiare persino l''hardware.
Da non molto tempo sono infine comparsi dei nuovi tipi di virus, i cosiddetti Virus delle Macro che si appiccicano a file documento generati per esempio con Microsoft Word per Windows, Microsoft Excel ecc...','Come difendersi dai virus<<-->>1) Limitare lo scambio di file .EXE, .COM, .OVR, .OVL, .SYS, .DOC, .XLS e di sistema (.SYS) fra computer in rete ed evitare di usare i server di rete come ambienti di lavoro. 
2) Ridurre l''uso di programmi shareware e di pubblico dominio se non se ne conosce la provenienza. 
3) Non inserire il proprio "disco sistema" in un altro computer se non in condizione di "protezione in scrittura" e non aggiungere mai dati o file ai floppy contenenti programmi originali. 
4) Non eseguire mai programmi di origine sconosciuta. Se proprio lo si dovesse fare, avvalersi di un programma antivirus di "SCANSIONE" in modo di rilevare la eventuale presenza di virus. ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'I virus informatici esistono da che si sono sviluppati i computer e l''informatica (primi anni ''80).<->T<<-->>I virus informatici  si diffondono tramite il trasferimento di files infetti da un computer ad un altro, ma non possono attaccare computers collegati fra loro in rete.<->F<<-->>I virus informatici, hanno sia poteri distruttivi che di ostruzionismo<->T<<-->>I virus attuali, al contrario di quelli di prima generazione,  attaccano solo i fili eseguibili.<->F<<-->>I virus attuali, al contrario di quelli di prima generazione, sono in grado di danneggiare anche l''hardware e la RAM.<->T<<-->>I virus della Macro sono un esempio di virus di prima generazione.<->F<<-->>I virus della macro sono molto pericolosi perché si possono facilmente trasmettere mediante lo scambio di files di tipo "documento" (es. posta elettronica).<->T<<-->>Tra le regole basilari di prevenzione dei virus informatici c''è la seguente: non utilizzare i file server di rete come stazioni di lavoro.<->T<<-->>Tra le regole di prevenzione c''è la seguente: utilizzare liberamente programmi shareware e di pubblico dominio.<->F<<-->>Tra le regole di prevenzione c''è la seguente: non eseguire mai programmi di origine sconosciuta. Se proprio lo si dovesse fare, avvalersi di un programma antivirus di "SCANSIONE" che esamini il contenuto del diskette in modo di rilevare la eventuale presenza di virus.<->T',0,3);

INSERT INTO `lesson` VALUES (9,4,'GDPR','Cos''è:<<-->>Il GDPR (General Data Protection Regulation) è il regolamento europeo sulla privacy operativo dal 25 maggio 2018. Esso prevede nuove regole per il trattamento di dati personali e stabilisce pesanti sanzioni per i trasgressori (privati o aziende). Essendo un regolamento (atto legislativo dell’Unione Europea insieme a direttive e decisioni), ha portata generale (in tutti i paesi dell’Unione) e applicabilità diretta.
Si compone di 99 articoli, in cui, oltre a istituire la figura del “data protection officer”, responsabile dell’applicazione del Regolamento in ciascuna azienda, stabilisce nuove regole e nuovi diritti degli utenti.','A chi si applica:<<-->>L’impatto è più ampio di quanto si possa pensare: Il GDPR riguarda infatti tutte le aziende che gestiscono qualsiasi tipo di dato personale. Dalle informazioni sui propri dipendenti alla profilatura dei clienti per conto terzi, o ancora all’analisi di dati per attività di marketing.
Le aziende che trasgrediscono tale regolamento possono incorrere in sanzioni fino a 20 milioni di euro, o, in caso di aziende più grandi, fino al 4% del fatturato.','Cosa cambia: nuove regole...<<-->>Secondo il nuovo regolamento, quando un''azienda cerca di accedere a dati personali, deve chiedere il consenso con «un linguaggio semplice e chiaro» (articolo 7), oltre a spiegare bene perché e a quale fine utilizzerà alcune informazioni (articolo 13). Deve anche dichiarare il «periodo di conservazione»: ovvero per quanto tempo si custodiranno i dati, fornendo all''utente un ulteriore elemento di valutazione per cedere o meno informazioni a proprio riguardo. Infine, in caso di violazione dei propri dati, il titolare è tenuto a notificare l’accaduto entro 72 ore.
Gli utenti potranno accedere quindi a molte più informazioni sul trattamento dei propri dati, senza doverle cercare in kilometriche e complesse informative.','...e nuovi diritti<<-->>Tra i diritti per i cittadini introdotti dal GDPR vi sono anche: il diritto di accesso (articolo 15: il cittadino deve poter sapere subito come e perché stanno trattando i suoi dati), il diritto di rettifica (articolo 16: «la rettifica dei dati personali inesatti che lo riguardano»), diritto di oblio (articolo 17: l''utente può far cancellare i dati in suo proposito) e il diritto alla portabilità dei dati (articolo 20: l''utente può ricevere tutte le informazioni che lo riguardano e trasmetterle a un altro titolare). ',NULL,NULL,NULL,NULL,NULL,NULL,'GDPR sta per<->General Data Protection Regulation<->Gender Discrimination PRevention<->Generational Drugs Producers Reabilitation<->Great Dalmatas PRoject<<-->>E’ stato emanato da<->Unione Europea<->Parlamento italiano<->Garante della Privacy<->È presente nella Costituzione Italiana<<-->>Il GDPR riguarda<->Tutte le aziende che trattano dati personali<->Enti statali e istituzioni<->Social Networks<->Aziende con fatturato superiore ai 20 milioni di euro annui<<-->>In caso di trasgressione, le sanzioni<->Arrivano fino a 20 milioni di euro (o al 4% del fatturato)<->Sono a carico dello Stato<->Sono proporzionali al fatturato dell’azienda<->Sono sempre inferiori a 10 milioni di euro<<-->>Il GDPR istituisce la figura del “data protection officer”, responsabile dell’applicazione del Regolamento in ciascuna azienda<->T<<-->>L’azienda che utilizza i dati personali non ha l’obbligo di comunicare il cd. «periodo di conservazione» ovvero per quanto tempo si custodiranno i dati stessi<->F<<-->>Il diritto di accesso prevede che il cittadino deve poter sapere subito come e perché stanno trattando i suoi dati<->T<<-->>Il GDPR non prevede il diritto di rettifica – vale a dire la possibilità per il cittadino di chiedere la rettifica dei dati personali inesatti che lo riguardano<->F<<-->>Un altro diritto previsto dalla normativa è quello di oblio, in base al quale l''utente può far cancellare i dati in suo proposito<->T<<-->>Il GDPR non ha concesso il diritto alla portabilità dei dati, in base al quale l''utente potrebbe ricevere tutte le informazioni che lo riguardano e trasmetterle a un altro titolare<->F',0,4);
INSERT INTO `lesson` VALUES (11,4,'VPN','Cos''è e come funziona<<-->>La VPN, nata per le aziende ma ora usata anche dai privati per aumentare la sicurezza via Internet, crea un tunnel virtuale tra il nostro computer e un server sicuro di proprietà del fornitore del servizio VPN. Tutto il traffico passa in modo criptato dal computer al server, per poi uscire “normalmente” su Internet. In sintesi, questo permette di navigare in modo privato e sicuro anche nelle reti Wi-Fi pubbliche. Grazie alla VPN, la navigazione Internet risulterà  provenire da un anonimo data center invece che dall’indirizzo IP intestato al sig. ‘Mario Rossi’.','Vantaggi e svantaggi <<-->>Oltra alla maggiore sicurezza informatica e alla protezione dei propri dati personali, la VPN permette di eludere le barriere geografiche. Infatti, praticamente tutti i servizi VPN, forniscono server in svariati Paesi. Con la VPN si può vedere un video sul sito della BBC, scegliendo un server nel Regno Unito, senza che il contenuto sia bloccato. Lo stesso vale per un sito negli Stati Uniti, o in Francia, o in Germania.
Uno svantaggio  del navigare in rete attraverso la VPN è la limitata banda a disposizione e una certa lentezza nel collegarsi alle pagine web., lentezza dovuta al fatto che l’attività di codifica e decodifica dei dati criptati richiede del tempo.','Fattori da considerare<<-->>1) Disponibilità di Paesi:  si consiglia di scegliere un servizio VPN con almeno 25 paesi, verificando che siano inclusi i paesi utilizzati più spesso: Stati Uniti, Regno Unito, Germania, Paesi Bassi.
2) Numero di dispositivi collegabili: in base alle esigenze proprie e familiari il numero può cambiare, ma si consiglia almeno 5 dispositivi collegabili.
3) Costo: confrontate diversi provider guardando anche il prezzo. Quasi tutti richiedono un pagamento mensile o annuale.','Come collegarsi alla VPN<<-->>Molti provider offrono una app per smartphone che consente un accesso facile dai dispositivi mobili. Qualora così non fosse, è comunque possibile configurare OpenVPN for Android in modo simile a quanto si fa con un PC.',NULL,NULL,NULL,NULL,NULL,NULL,'L''acronimo VPN sta per Very Powerful Network<->F<<-->>VPN nasce per le reti aziendali<->T<<-->>La VPN crea un tunnel virtuale tra il nostro computer e un server sicuro di proprietà del fornitore del servizio VPN<->T<<-->>Le informazioni escono criptate dal computer al server <->T<<-->>Usando VPN la navigazione risulterà generata da anonimo data center<->T<<-->>La protezione di VPN non funziona sulle reti pubbliche<->F<<-->>VPN non mitiga gli effetti della cd. ''sorveglianza di massa‘<->F<<-->>VPN permette di  ridurre gli effetti delle barriere geografiche<->T<<-->>Tra i fattori da considerare nella scelta del servizio VPN è il numero di dispositivi collegabili mentre non ha importanza il numero di paesi disponibili<->F<<-->>Per collegarsi non è sempre necessario utilizzare una app fornita dal provider<->T',0,4);
CREATE TABLE IF NOT EXISTS `course` (
	`_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`title`	TEXT
);
INSERT INTO `course` VALUES (1,'Key Concepts');
INSERT INTO `course` VALUES (2,'Cyber Attacks');
INSERT INTO `course` VALUES (4,'Privacy');
COMMIT;
